"""Add phone and attachments

Revision ID: d94f089501de
Revises: 9459a6f6a530
Create Date: 2026-08-17 11:07:29.190456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94f089501de'
down_revision: Union[str, Sequence[str], None] = '9459a6f6a530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communications', sa.Column('attachment_name', sa.String(), nullable=True))
    op.add_column('communications', sa.Column('attachment_path', sa.String(), nullable=True))
    op.add_column('communications', sa.Column('attachment_size', sa.Integer(), nullable=True))
    op.add_column('communications', sa.Column('attachment_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('communications', 'attachment_type')
    op.drop_column('communications', 'attachment_size')
    op.drop_column('communications', 'attachment_path')
    op.drop_column('communications', 'attachment_name')
    # ### end Alembic commands ###
